apiVersion: v1
kind: Pod
metadata:
  name: voting-app-worker-pod
  labels:
      name: voting-app-worker-pod
      app: demo-voting-app
spec:
  containers:
    - name: voting-app-worker
      image: docker/example-voting-app-worker
      ports:
        - containerPort: 80